title: Noah Lewis (Personal Website)

description: >
  Welcome to my personal webiste 👋. On this site I plan to blog about my ongoing research and career progress. 
  Feel free to stick around of you are interested in high level computer science research!!!

header_pages:
  - about.md

theme: minima
