title: Noah Lewis (Personal Website)
author :
  name : Noah Lewis
  email : nlewi26@lsu.edu
  github : TheAssembler1
header_pages:
  - about.md

remote_theme: jekyll/minima

minima:
  skin: dark