title: Noah Lewis (Personal Website)
author :
  name : Noah Lewis
  email : nlewi26@lsu.edu
  github : https://www.github.com/TheAssembler1
description: What the hell even is a circuit?
header_pages:
  - about.md
show_excerpts: true

remote_theme: jekyll/minima

minima:
  skin: dark
