title: Noah Lewis (Personal Website)
author :
  name : Name Lastname
  email : blah@email.test
  github : username
  twitter : username
header_pages:
  - about.md

remote_theme: jekyll/minima

minima:
  skin: dark