title: Noah Lewis (Personal Website)
author :
  name : Noah Lewis
  email : nlewi26@lsu.edu
  github : https://www.github.com/TheAssembler1
description: >
  I currently attend Louisiana State University (LSU) and entering my last semster at the college. Afterwards, 
  I plan to pursue a PHD at Ohio State Univeristy (OSU) under the advisory of Suren Byna. My research will 
  revolve around HPC I/O.
header_pages:
  - about.md
show_excerpts: true

remote_theme: jekyll/minima

minima:
  skin: dark
