author: Noah Lewis

social-network-links:
  email: "nlewi26@lsu.edu"
  
share-links-active:
  email: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  
      social-share: true 

theme: minima
